title: Philip Ball
description: AI Resident @ Microsoft
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
theme: jekyll-theme-cayman

# Icons in the footer for contacting
social-network-links:
  email: "philipjball93@gmail.com"
#  facebook: 
  github: fiorenza2
#  twitter: daattali
#  reddit: yourname
#  google-plus: +DeanAttali
  linkedin: philipjohnball
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname